// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ectnxobligjctxgzgwvc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVjdG54b2JsaWdqY3R4Z3pnd3ZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0MTEzNDUsImV4cCI6MjA3MDk4NzM0NX0.AwQNOrQAwQRTYOjwOlJZt3onDrs8OzteaxVMfIpJd5U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});